---
dependencies:
- name: "activiti-cloud-identity"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "0.0.11"
- name: "activiti-cloud-gateway"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.19"
  condition: "infrastructure.activiti-cloud-gateway.enabled,activiti-cloud-gateway.enabled"
- name: "activiti-cloud-query"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.319"
  condition: "application.activiti-cloud-query.enabled,activiti-cloud-query.enabled"
- name: "activiti-cloud-audit"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.311"
  condition: "application.activiti-cloud-audit.enabled,activiti-cloud-audit.enabled"
- name: "activiti-cloud-messages"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.34"
  condition: "activiti-cloud-messages.enabled"
- name: "rabbitmq-ha"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "1.38.1"
  condition: "application.rabbitmq.enabled,rabbitmq.enabled"
  alias: "rabbitmq"
- name: "postgresql"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "3.11.3"
  condition: "application.postgres.enabled,postgres.enabled"
  alias: "postgres"
- name: "activiti-cloud-notifications-graphql"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.344"
  condition: "application.activiti-cloud-notifications-graphql.enabled,activiti-cloud-notifications-graphql.enabled"
